# Generated by Django 3.1.7 on 2021-02-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210225_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'PENDING'), (1, 'APPROVED'), (2, 'REJECTED')], default=1, verbose_name='Reason'),
            preserve_default=False,
        ),
    ]
