# Generated by Django 3.1.7 on 2021-02-26 11:09

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210226_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_requests', to=settings.AUTH_USER_MODEL, validators=[accounts.models.manager_validate]),
        ),
    ]
